declare const enum NotificationIcon {
    PaintBrush,
    ETO = 2,
    ETORed = 3,
    TechPoint = 4,
    Shield = 8,
    Star = 9,
    V = 11,
    Package = 13,
    BlueStar = 14,
    PaintBrushRed = 15,
    Nothing = 17,
    WatchDogsGold = 22,
    Skull = 25,
    OrangeMarker = 33,
}
